# Generated by Django 4.2.30 on 2026-05-01 05:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_rekening', models.CharField(max_length=10, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('pemilik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekening', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('transfer', 'Transfer Dana'), ('topup', 'Top-up')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('waktu_diproses', models.DateTimeField(blank=True, null=True)),
                ('catatan_staff', models.TextField(blank=True)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_diproses', to=settings.AUTH_USER_MODEL)),
                ('rekening_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaksi_keluar', to='banking.rekening')),
                ('rekening_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaksi_masuk', to='banking.rekening')),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank Lain'), ('virtual', 'Virtual Account')], default='tunai', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Proses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('waktu_request', models.DateTimeField(auto_now_add=True)),
                ('waktu_proses', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_diproses', to=settings.AUTH_USER_MODEL)),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_set', to='banking.rekening')),
            ],
            options={
                'ordering': ['-waktu_request'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
    ]
